name: first-workflow
on: 
      push:
            branches:
            - main
      pull_request:
            branches:
            - main
            
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Run
        run: npm ci
      - name: test
        run: npm test      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: first artifact
          path: main
  Deploy:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: first artifact
          path: main
      - name: Build project
        run: echo "Build project"
      - name: Deploy
        run: echo "Deploying.."
  
        
      
