name: first-workflow
on: 
      push:
            branches:
            - main
      pull_request:
            branches:
            - main
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      ##- name: composite action
        ##uses: ./.github/workflows
      - name: create data
        run: |
            printf '{
              "data_1": "Text data",
              "data_2": true
              }' >> testartifact.json
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
        
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testartifact.json
          path: ./
      - name: Test the build
        id: vars
        run: echo  "version=$(cat testartifact.json)" >> $GITHUB_OUTPUT

          
  
  Deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: testartifact.json
          path: main
      - name: Build project
        run: echo "Build project"
      - name: Deploy
        run: echo "Deploying.."
  
        
      
