name: first-workflow
on: 
      push:
            branches:
            - main
      pull_request:
            branches:
            - main
            
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Install java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ant -noinput -buildfile settings.xml
      - uses: actions/upload-artifact@v4
        with:
           name: package
           path: build/jar
    
  Deploy:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: first artifact
          path: main
      - name: Build project
        run: echo "Build project"
      - name: Deploy
        run: echo "Deploying.."
  
        
      
